version: '3.3'

services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
