version: '3.3'

services:
  db:
    image: postgres:10.5
    environment:
      - POSTGRES_DB
      - POSTGRES_USER=wallabag
      - POSTGRES_PASSWORD=DB_PASS
      - PGDATA
      - POSTGRES_INITDB_ARGS
      - POSTGRES_INITDB_WALDIR
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
